import express from 'express';
import cors from 'cors';
import path from 'path';
import { GraphClient } from '../db/graph-client.ts';
import { RAGService } from '../ai/rag-service.ts';
import { IngestionService } from '../ingestion/ingestion-service.ts';
import { DocGenerator } from '../ai/doc-generator.ts';
import fs from 'fs/promises';

const GRAPHHUB_API_KEY = process.env.GRAPHHUB_API_KEY;
if (!GRAPHHUB_API_KEY) {
  console.error('WARNING: GRAPHHUB_API_KEY environment variable is not set. The /api/find-purpose endpoint will reject all requests.');
}
const PROJECTS_FILE = './.graphhub/projects.json';

interface Project {
  id: string;
  name: string;
  path: string;
  indexedAt: string;
  functionCount: number;
  fileCount: number;
  languages: string[];
}

export class GraphHubAPIServer {
  private app: express.Application;
  private db: GraphClient;
  private _rag: RAGService | null = null;

  private getRag(): RAGService {
    if (!this._rag) this._rag = RAGService.getInstance();
    return this._rag;
  }

  constructor() {
    this.app = express();
    this.db = GraphClient.getInstance();
    this.app.use(cors());
    this.app.use(express.json());
    this.setupRoutes();
  }

  public async initialize(): Promise<void> {
    // Test database connection
    try {
      const result = await this.db.runCypher('MATCH (n) RETURN count(n) as cnt LIMIT 1');
      const rows = await result.getAll();
      console.error(`Database connected. Node count: ${rows[0]?.cnt || 0}`);
    } catch (err: any) {
      console.error('Database connection test failed:', err.message);
      throw err;
    }
  }

  private async loadProjects(): Promise<Project[]> {
    try {
      const data = await fs.readFile(PROJECTS_FILE, 'utf-8');
      return JSON.parse(data);
    } catch {
      return [];
    }
  }

  private async saveProjects(projects: Project[]): Promise<void> {
    await fs.mkdir(path.dirname(PROJECTS_FILE), { recursive: true });
    await fs.writeFile(PROJECTS_FILE, JSON.stringify(projects, null, 2));
  }

  private async generateCodebaseMd(projectPath: string): Promise<void> {
    try {
      // Get all functions for this workspace
      const cypher = `
        MATCH (f:File)-[:CONTAINS]->(s:Symbol)
        WHERE s.kind IN ['function', 'method'] AND f.path STARTS WITH $path
        RETURN s.name as name, s.kind as kind, s.inputs as inputs, s.outputs as outputs,
               s.calls as calls, f.path as filePath
        ORDER BY f.path ASC, s.name ASC
      `;
      const result = await this.db.runCypher(cypher, { path: projectPath });
      const functions = await result.getAll();

      // Get file stats
      const filesResult = await this.db.runCypher(
        'MATCH (f:File) WHERE f.path STARTS WITH $path RETURN f.path as path, f.language as language',
        { path: projectPath }
      );
      const files = await filesResult.getAll();

      // Group functions by file
      const fileMap = new Map<string, any[]>();
      for (const fn of functions) {
        const fileName = fn.filePath.replace(/\\/g, '/').split('/').pop() || 'unknown';
        if (!fileMap.has(fileName)) fileMap.set(fileName, []);
        fileMap.get(fileName)!.push(fn);
      }

      // Generate markdown
      const projectName = projectPath.replace(/\\/g, '/').split('/').pop() || 'Project';
      const languages = [...new Set(files.map((f: any) => f.language).filter(Boolean))];

      let md = `# ${projectName} - Codebase Overview

> Auto-generated by GraphHub on ${new Date().toISOString().split('T')[0]}

## Summary

| Metric | Value |
|--------|-------|
| Total Files | ${files.length} |
| Total Functions | ${functions.length} |
| Languages | ${languages.join(', ') || 'N/A'} |

## File Structure

`;

      for (const [fileName, fns] of fileMap) {
        md += `### ${fileName}\n\n`;
        md += `| Function | Inputs | Outputs | Calls |\n`;
        md += `|----------|--------|---------|-------|\n`;

        for (const fn of fns) {
          const inputs = Array.isArray(fn.inputs) ? fn.inputs.join(', ') : '';
          const outputs = Array.isArray(fn.outputs) ? fn.outputs.join(', ') : '';
          const calls = Array.isArray(fn.calls) ? fn.calls.slice(0, 5).join(', ') + (fn.calls.length > 5 ? '...' : '') : '';
          md += `| \`${fn.name}\` | ${inputs || '-'} | ${outputs || '-'} | ${calls || '-'} |\n`;
        }
        md += '\n';
      }

      md += `## Function Call Graph

The following functions have the most outgoing calls:

`;
      // Top callers
      const sorted = [...functions].sort((a, b) => (b.calls?.length || 0) - (a.calls?.length || 0)).slice(0, 10);
      for (const fn of sorted) {
        if (fn.calls?.length > 0) {
          md += `- **${fn.name}** calls: ${fn.calls.join(', ')}\n`;
        }
      }

      md += `
---
*This file was generated by [GraphHub](https://github.com/graphhub) for AI agent consumption.*
`;

      // Write to project directory
      const mdPath = path.join(projectPath, 'codebase.md');
      await fs.writeFile(mdPath, md, 'utf-8');
      console.log(`Generated codebase.md at ${mdPath}`);
    } catch (err: any) {
      console.error('Failed to generate codebase.md:', err.message);
    }
  }

  private setupRoutes() {
    this.app.get('/api/workspaces', async (req, res) => {
      try {
        const result = await this.db.runCypher('MATCH (f:File) RETURN DISTINCT f.path AS path');
        const paths = (await result.getAll()).map((r: any) => r.path);
        const roots = new Set<string>();
        for (const p of paths) {
          const sep = p.lastIndexOf('\\') !== -1 ? '\\' : '/';
          const dir = p.substring(0, p.lastIndexOf(sep));
          if (dir) roots.add(dir.split(/\/|\\/).slice(0, -1).join('/'));
        }
        res.json({ workspaces: Array.from(roots) });
      } catch (err: any) {
        res.status(500).json({ error: err.message });
      }
    });

    // ── GET /api/projects ─────────────────────────────────────────────────────
    // Returns list of saved projects (codebases)
    this.app.get('/api/projects', async (req, res) => {
      try {
        const projects = await this.loadProjects();
        res.json({ projects });
      } catch (err: any) {
        res.status(500).json({ error: err.message });
      }
    });

    // ── DELETE /api/projects/:id ──────────────────────────────────────────────
    // Remove a project from saved list
    this.app.delete('/api/projects/:id', async (req, res) => {
      try {
        const { id } = req.params;
        const projects = await this.loadProjects();
        const filtered = projects.filter(p => p.id !== id);
        await this.saveProjects(filtered);
        res.json({ status: 'success' });
      } catch (err: any) {
        res.status(500).json({ error: err.message });
      }
    });

    this.app.post('/api/index', async (req, res) => {
      try {
        const { targetDir } = req.body;
        if (!targetDir) {
          res.status(400).json({ error: 'targetDir is required' });
          return;
        }
        const normalizedPath = path.resolve(targetDir);
        console.log(`Starting in-process indexing for ${normalizedPath}...`);

        const ingestion = new IngestionService();
        await ingestion.initialize();
        await ingestion.indexDirectory(normalizedPath);
        await ingestion.resolveImports();
        await ingestion.resolveCalls();
        await ingestion.resolveInheritance();
        console.log(`Indexing for ${normalizedPath} completed.`);

        // Get stats for the project
        const funcResult = await this.db.runCypher(
          "MATCH (f:File)-[:CONTAINS]->(s:Symbol) WHERE f.path STARTS WITH $path AND s.kind IN ['function', 'method'] RETURN count(s) as cnt",
          { path: normalizedPath }
        );
        const funcRows = await funcResult.getAll();
        const functionCount = funcRows[0]?.cnt || 0;

        const fileResult = await this.db.runCypher(
          'MATCH (f:File) WHERE f.path STARTS WITH $path RETURN count(f) as cnt, collect(DISTINCT f.language) as langs',
          { path: normalizedPath }
        );
        const fileRows = await fileResult.getAll();
        const fileCount = fileRows[0]?.cnt || 0;
        const languages = fileRows[0]?.langs?.filter(Boolean) || [];

        // Save project
        const projects = await this.loadProjects();
        const projectName = normalizedPath.replace(/\\/g, '/').split('/').pop() || 'Unknown';
        const projectId = Buffer.from(normalizedPath).toString('base64').replace(/[/+=]/g, '');

        // Update or add project
        const existingIdx = projects.findIndex(p => p.path === normalizedPath);
        const project: Project = {
          id: projectId,
          name: projectName,
          path: normalizedPath,
          indexedAt: new Date().toISOString(),
          functionCount,
          fileCount,
          languages
        };

        if (existingIdx >= 0) {
          projects[existingIdx] = project;
        } else {
          projects.unshift(project);
        }
        await this.saveProjects(projects);

        // Generate codebase.md for AI agents
        await this.generateCodebaseMd(normalizedPath);

        res.json({ status: 'success', project });
      } catch (err: any) {
        console.error('Indexing failed:', err);
        res.status(500).json({ error: err.message });
      }
    });

    this.app.get('/api/graph', async (req, res) => {
      try {
        const workspace = req.query.workspace as string | undefined;
        // Optimize graph for performance: Only fetch Symbols and Files by default
        // Exclude IMPORTS and other overhead nodes that cause frontend hangs on large projects
        const nodesRes = await this.db.runCypher(
          "MATCH (n) WHERE (label(n) = 'Symbol' OR label(n) = 'File') " +
          "AND (n.name IS NULL OR n.name <> 'anonymous') RETURN n"
        );
        const relsRes = await this.db.runCypher(
          "MATCH (a)-[r]->(b) " +
          "WHERE (label(a) = 'Symbol' OR label(a) = 'File') " +
          "AND (label(b) = 'Symbol' OR label(b) = 'File') " +
          "RETURN r"
        );
        let allNodes = await nodesRes.getAll();
        let allRels = await relsRes.getAll();

        if (workspace) {
          const normWorkspace = workspace.replace(/\\/g, '/');
          allNodes = allNodes.filter((r: any) => {
            const row = r['n'];
            if (row._label === 'File') return row.path.replace(/\\/g, '/').startsWith(normWorkspace);
            if (row._label === 'Symbol') return row.id.replace(/\\/g, '/').startsWith(normWorkspace);
            if (row._label === 'Chunk') return row.id.replace(/\\/g, '/').startsWith(`chunk:${normWorkspace}`);
            return false;
          });
          const validOffsets = new Set(allNodes.map((r: any) => r['n']._id.offset.toString()));
          allRels = allRels.filter((r: any) =>
            validOffsets.has(r['r']._src.offset.toString()) && validOffsets.has(r['r']._dst.offset.toString())
          );
        }

        const chunks = allNodes.filter((r: any) => r['n']._label === 'Chunk');
        const describesRels = allRels.filter((r: any) => r['r']._label === 'DESCRIBES');
        const docMap = new Map();
        for (const rel of describesRels) {
          const chunkId = rel['r']._src.offset.toString();
          const symbolId = rel['r']._dst.offset.toString();
          const chunk = chunks.find((c: any) => c['n']._id.offset.toString() === chunkId);
          if (chunk) docMap.set(symbolId, chunk['n'].text);
        }

        // Build symbol-offset → fileName map via CONTAINS relationships
        const containsRels = allRels.filter((r: any) => r['r']._label === 'CONTAINS');
        const fileNodes = allNodes.filter((r: any) => r['n']._label === 'File');
        const fileOffsetToName = new Map<string, string>();
        for (const fn of fileNodes) {
          const p: string = fn['n'].path || '';
          const sep = p.lastIndexOf('\\') !== -1 ? '\\' : '/';
          fileOffsetToName.set(fn['n']._id.offset.toString(), p.substring(p.lastIndexOf(sep) + 1));
        }
        const symbolToFileName = new Map<string, string>();
        for (const rel of containsRels) {
          const fileOffset = rel['r']._src.offset.toString();
          const symOffset = rel['r']._dst.offset.toString();
          const name = fileOffsetToName.get(fileOffset);
          if (name) symbolToFileName.set(symOffset, name);
        }

        // Filter out Chunks, anonymous functions, imports, and file_module for cleaner graph
        const nodes = allNodes
          .filter((row: any) => row['n']._label !== 'Chunk')
          .filter((row: any) => {
            if (row['n']._label === 'Symbol') {
              // Skip anonymous functions
              if (row['n'].name === 'anonymous') return false;
              // Skip import nodes - they clutter the graph
              if (row['n'].kind === 'import') return false;
              // Skip file_module fallback nodes
              if (row['n'].kind === 'file_module') return false;
            }
            return true;
          })
          .map((row: any) => {
          const id = row['n']._id?.offset.toString() || row['n'].id || row['n'].path;
          const fileName = row['n']._label === 'Symbol'
            ? symbolToFileName.get(row['n']._id?.offset.toString()) || null
            : null;
          return {
            id,
            type: 'customNode',
            data: {
              label: row['n'].name || row['n'].path || row['n'].text?.substring(0, 20),
              type: row['n']._label,
              fileName,
              properties: { ...row['n'] },
            },
          };
        });

        const edges = allRels.filter((row: any) => row['r']._label !== 'DESCRIBES').map((row: any) => ({
          id: `e-${row['r']._src.offset}-${row['r']._dst.offset}`,
          source: row['r']._src.offset.toString(),
          target: row['r']._dst.offset.toString(),
          label: row['r']._label,
        }));

        res.json({ nodes, edges });
      } catch (err: any) {
        res.status(500).json({ error: err.message });
      }
    });

    this.app.post('/api/search', async (req, res) => {
      try {
        const { query } = req.body;
        const results = await this.getRag().search(query);
        res.json(results);
      } catch (err: any) {
        res.status(500).json({ error: err.message });
      }
    });

    this.app.get('/api/symbol/:id', async (req, res) => {
      try {
        const { id } = req.params;
        const symbolResult = await this.db.runCypher(
          'MATCH (f:File)-[:CONTAINS]->(s:Symbol {id: $id}) RETURN s, f.path as filePath',
          { id }
        );
        const rows = await symbolResult.getAll();
        if (rows.length === 0) {
          res.status(404).json({ error: `Symbol with ID '${id}' not found` });
          return;
        }

        const calleesResult = await this.db.runCypher(
          'MATCH (s:Symbol {id: $id})-[:CALLS]->(callee:Symbol) WHERE callee.name <> "anonymous" RETURN DISTINCT callee.name as name, callee.kind as kind',
          { id }
        );
        const callersResult = await this.db.runCypher(
          'MATCH (caller:Symbol)-[:CALLS]->(s:Symbol {id: $id}) WHERE caller.name <> "anonymous" RETURN DISTINCT caller.name as name, caller.kind as kind',
          { id }
        );

        const sym = rows[0]['s'];
        res.json({
          name: sym.name,
          kind: sym.kind,
          id: sym.id,
          filePath: rows[0].filePath,
          range: sym.range ? JSON.parse(sym.range) : null,
          inputs: sym.inputs || [],
          outputs: sym.outputs || [],
          purpose: sym.purpose || null,
          strategy: sym.strategy || null,
          technicalDebt: sym.technical_debt || [],
          status: sym.status || 'Done',
          callers: await callersResult.getAll(),
          callees: await calleesResult.getAll(),
        });
      } catch (err: any) {
        res.status(500).json({ error: err.message });
      }
    });

    this.app.get('/api/entry-points', async (req, res) => {
      try {
        const workspace = req.query.workspace as string | undefined;
        const cypher = [
          'MATCH (s:Symbol)',
          "WHERE s.kind IN ['function', 'method', 'class'] AND s.name <> 'anonymous'",
          'WITH s',
          'OPTIONAL MATCH (caller:Symbol)-[:CALLS]->(s)',
          'WITH s, count(caller) as callerCount',
          'RETURN s.name as name, s.kind as kind, s.purpose as purpose, s.id as id, callerCount',
          'ORDER BY callerCount ASC, s.name ASC',
        ].join(' ');
        const result = await this.db.runCypher(cypher);
        let rows = await result.getAll();
        if (workspace) {
          const normWorkspace = workspace.replace(/\\/g, '/');
          rows = rows.filter((r: any) => r.id?.replace(/\\/g, '/').startsWith(normWorkspace));
        }
        const entryPoints = rows
          .filter((r: any) => r.callerCount <= 1)
          .map((r: any) => ({ name: r.name, kind: r.kind, purpose: r.purpose, callerCount: Number(r.callerCount) }));
        res.json({ entryPoints });
      } catch (err: any) {
        res.status(500).json({ error: err.message });
      }
    });

    this.app.get('/api/trace/:name', async (req, res) => {
      try {
        const { name } = req.params;
        const depth = parseInt(req.query.depth as string) || 5;
        const startResult = await this.db.runCypher('MATCH (s:Symbol {name: $name}) RETURN s', { name });
        const startRows = await startResult.getAll();
        if (startRows.length === 0) {
          res.status(404).json({ error: `Symbol '${name}' not found` });
          return;
        }

        const buildTree = async (symbolName: string, currentDepth: number, visited: Set<string>): Promise<any> => {
          if (currentDepth > depth || visited.has(symbolName)) return null;
          visited.add(symbolName);
          const symResult = await this.db.runCypher('MATCH (s:Symbol {name: $name}) RETURN s', { name: symbolName });
          const symRows = await symResult.getAll();
          if (symRows.length === 0) return null;
          const sym = symRows[0]['s'];
          const calleesResult = await this.db.runCypher(
            'MATCH (s:Symbol {name: $name})-[:CALLS]->(callee:Symbol) WHERE callee.name <> "anonymous" RETURN DISTINCT callee.name as name',
            { name: symbolName }
          );
          const calleeRows = await calleesResult.getAll();
          const children = [];
          for (const callee of calleeRows) {
            const child = await buildTree(callee.name, currentDepth + 1, new Set(visited));
            if (child) children.push(child);
          }
          return {
            name: sym.name, kind: sym.kind, purpose: sym.purpose || null,
            strategy: sym.strategy || null, inputs: sym.inputs || [],
            outputs: sym.outputs || [], depth: currentDepth, children,
          };
        };

        const trace = await buildTree(name, 0, new Set());
        res.json({ trace });
      } catch (err: any) {
        res.status(500).json({ error: err.message });
      }
    });

    // ── GET /api/functions ────────────────────────────────────────────────────
    // Returns all indexed functions with structured metadata:
    // name, kind, inputs, outputs, calls (functions it invokes), and file location.
    // NOTE: "purpose" is intentionally excluded - available only via /api/find-purpose (API key required).
    this.app.get('/api/functions', async (req, res) => {
      try {
        const workspace = req.query.workspace as string | undefined;

        // Query functions with their metadata
        const cypher = "MATCH (file:File)-[:CONTAINS]->(sym:Symbol) WHERE sym.kind IN ['function', 'method'] AND sym.name <> 'anonymous' RETURN sym.name as name, sym.kind as kind, sym.inputs as inputs, sym.outputs as outputs, sym.range as range, sym.id as id, sym.calls as calls, file.path as filePath ORDER BY file.path ASC, sym.name ASC";
        const result = await this.db.runCypher(cypher);
        let rows = await result.getAll();

        if (workspace) {
          const normWorkspace = workspace.replace(/\\/g, '/');
          rows = rows.filter((r: any) => r.filePath?.replace(/\\/g, '/').startsWith(normWorkspace));
        }

        const functions = rows.map((r: any) => {
          let rangeObj: any = { start: { row: 0 } };
          try { rangeObj = JSON.parse(r.range || '{}'); } catch {}
          const inputs: string[] = Array.isArray(r.inputs) ? r.inputs : [];
          const outputs: string[] = Array.isArray(r.outputs) ? r.outputs : [];
          // Use the calls array stored directly on the symbol
          const calls: string[] = Array.isArray(r.calls) ? r.calls.filter(Boolean) : [];
          const parts: string[] = r.filePath ? r.filePath.replace(/\\/g, '/').split('/') : ['unknown'];
          const fileName: string = parts[parts.length - 1] || 'unknown';
          return {
            name: r.name,
            kind: r.kind,
            inputs,
            outputs,
            calls,
            location: { file: r.filePath, fileName, line: (rangeObj.start?.row ?? 0) + 1 },
            id: r.id,
          };
        });

        res.json({ functions });
      } catch (err: any) {
        res.status(500).json({ error: err.message });
      }
    });

    // ── POST /api/find-purpose ────────────────────────────────────────────────
    // Analyses a symbol's purpose using the code intelligence engine.
    // Requires a valid x-api-key header matching GRAPHHUB_API_KEY.
    this.app.post('/api/find-purpose', async (req, res) => {
      const providedKey = req.headers['x-api-key'] as string | undefined;
      if (!GRAPHHUB_API_KEY || !providedKey || providedKey !== GRAPHHUB_API_KEY) {
        res.status(401).json({ error: 'Invalid or missing API key' });
        return;
      }
      try {
        const { id } = req.body;
        if (!id) {
          res.status(400).json({ error: 'id is required' });
          return;
        }

        const symbolResult = await this.db.runCypher(
          'MATCH (f:File)-[:CONTAINS]->(s:Symbol {id: $id}) RETURN s, f.path as filePath',
          { id }
        );
        const rows = await symbolResult.getAll();
        if (rows.length === 0) {
          res.status(404).json({ error: `Symbol with ID '${id}' not found` });
          return;
        }

        const sym = rows[0]['s'];
        const filePath: string = rows[0].filePath;

        // Read the source slice for this symbol
        let sourceCode = '';
        try {
          let rangeObj: any = {};
          try { rangeObj = JSON.parse(sym.range || '{}'); } catch {}
          const content = await fs.readFile(filePath, 'utf8');
          const lines = content.split('\n');
          sourceCode = lines.slice(rangeObj.start?.row ?? 0, (rangeObj.end?.row ?? 0) + 1).join('\n');
        } catch {}

        // Generate purpose using the heuristic engine (no external API call needed)
        const generator = new DocGenerator({ provider: 'heuristic' });
        let parsedRange: any = {};
        try { parsedRange = sym.range ? JSON.parse(sym.range) : {}; } catch (e) { parsedRange = {}; }
        const doc = await generator.generateDocForSymbol({
          id: sym.id,
          name: sym.name,
          kind: sym.kind,
          filePath,
          range: parsedRange,
          sourceCode,
        });

        // Persist so future graph queries show the result
        await generator.saveDoc(sym.id, doc);
        res.json({ purpose: doc.purpose, strategy: doc.strategy });
      } catch (err: any) {
        res.status(500).json({ error: err.message });
      }
    });

    // ── DELETE /api/workspace ─────────────────────────────────────────────────
    // Clear all data for a workspace before re-indexing
    this.app.delete('/api/workspace', async (req, res) => {
      try {
        const workspace = req.query.workspace as string | undefined;
        if (!workspace) {
          res.status(400).json({ error: 'workspace query parameter is required' });
          return;
        }
        const normWorkspace = workspace.replace(/\\/g, '/');

        // Delete all symbols, chunks, and relationships for this workspace
        await this.db.runCypher(
          'MATCH (f:File) WHERE f.path STARTS WITH $path ' +
          'OPTIONAL MATCH (f)-[:CONTAINS]->(s:Symbol) ' +
          'OPTIONAL MATCH (c:Chunk)-[:DESCRIBES]->(s) ' +
          'DETACH DELETE f, s, c',
          { path: workspace }
        );

        // Also try with normalized path
        await this.db.runCypher(
          'MATCH (f:File) WHERE f.path STARTS WITH $path ' +
          'OPTIONAL MATCH (f)-[:CONTAINS]->(s:Symbol) ' +
          'OPTIONAL MATCH (c:Chunk)-[:DESCRIBES]->(s) ' +
          'DETACH DELETE f, s, c',
          { path: normWorkspace }
        );

        // Clear file hash records for this workspace
        await this.db.runCypher(
          'MATCH (h:FileHash) WHERE h.path STARTS WITH $path DETACH DELETE h',
          { path: workspace }
        ).catch(() => {});

        console.log(`Cleared workspace data for: ${workspace}`);
        res.json({ status: 'success', message: `Cleared data for ${workspace}` });
      } catch (err: any) {
        res.status(500).json({ error: err.message });
      }
    });

    // ── POST /api/save-custom-md ──────────────────────────────────────────────
    // Save a customized graph view as markdown file for AI agents
    this.app.post('/api/save-custom-md', async (req, res) => {
      try {
        const { workspace, visibleFunctions, fileName } = req.body;
        if (!workspace || !visibleFunctions || !fileName) {
          res.status(400).json({ error: 'workspace, visibleFunctions array, and fileName are required' });
          return;
        }

        const normWorkspace = workspace.replace(/\\/g, '/');
        const projectName = normWorkspace.split('/').pop() || 'Project';

        // Get function details for visible functions
        const cypher = `
          MATCH (f:File)-[:CONTAINS]->(s:Symbol)
          WHERE s.kind IN ['function', 'method'] AND s.name <> 'anonymous'
          AND f.path STARTS WITH $path
          RETURN s.name as name, s.kind as kind, s.inputs as inputs, s.outputs as outputs,
                 s.calls as calls, f.path as filePath
          ORDER BY f.path ASC, s.name ASC
        `;
        const result = await this.db.runCypher(cypher, { path: workspace });
        const allFunctions = await result.getAll();

        // Filter to only visible functions
        const visibleSet = new Set(visibleFunctions);
        const functions = allFunctions.filter((fn: any) => visibleSet.has(fn.name));

        // Group by file
        const fileMap = new Map<string, any[]>();
        for (const fn of functions) {
          const fName = fn.filePath.replace(/\\/g, '/').split('/').pop() || 'unknown';
          if (!fileMap.has(fName)) fileMap.set(fName, []);
          fileMap.get(fName)!.push(fn);
        }

        // Generate markdown
        let md = `# ${projectName} - Custom Graph View

> Generated by GraphHub on ${new Date().toISOString().split('T')[0]}
> This is a customized view with ${functions.length} selected functions.

## Selected Functions

`;

        for (const [fName, fns] of fileMap) {
          md += `### ${fName}\n\n`;
          md += `| Function | Inputs | Outputs | Calls |\n`;
          md += `|----------|--------|---------|-------|\n`;

          for (const fn of fns) {
            const inputs = Array.isArray(fn.inputs) ? fn.inputs.join(', ') : '';
            const outputs = Array.isArray(fn.outputs) ? fn.outputs.join(', ') : '';
            // Filter calls to only include visible functions
            const calls = Array.isArray(fn.calls)
              ? fn.calls.filter((c: string) => visibleSet.has(c)).join(', ')
              : '';
            md += `| \`${fn.name}\` | ${inputs || '-'} | ${outputs || '-'} | ${calls || '-'} |\n`;
          }
          md += '\n';
        }

        md += `## Call Flow

\`\`\`mermaid
graph TD
`;
        // Add mermaid diagram for visible functions only
        for (const fn of functions) {
          if (fn.calls && Array.isArray(fn.calls)) {
            for (const callee of fn.calls) {
              if (visibleSet.has(callee)) {
                md += `    ${fn.name}["${fn.name}()"] --> ${callee}["${callee}()"]\n`;
              }
            }
          }
        }
        md += `\`\`\`

---
*Custom view saved by user via [GraphHub](https://github.com/graphhub)*
`;

        // Save the file
        const mdPath = path.join(workspace, fileName.endsWith('.md') ? fileName : `${fileName}.md`);
        await fs.writeFile(mdPath, md, 'utf-8');
        console.log(`Saved custom graph to ${mdPath}`);

        res.json({ status: 'success', path: mdPath, functionCount: functions.length });
      } catch (err: any) {
        res.status(500).json({ error: err.message });
      }
    });

    this.app.get('/health', (req, res) => {
      res.json({ status: 'ok' });
    });
  }

  public listen(port: number = 9000) {
    this.app.listen(port, () => {
      console.error("GraphHub API Server running on port " + port);
    });
  }
}